//постоянные
const MY_NAME = 'Дмитрий';
const MY_MIDDLENAME = 'Сергеевич';
const MY_SURNAME = 'Бойко';
const MY_CURRENT_AGE = '28';
const MY_HOMETOWN = 'Краматорск';
const MY_GENDER = 'мужской';
const MY_EYE_COLOR = 'карие';
const I_SMOKE = false;
//переменные
let my_age = 28;
let my_current_height = 192;
let my_current_weight = 106;
let my_current_nationality = 'украинец';
let my_current_town = 'Краматорск';
let my_current_street = 'б-р Краматорский';
let my_current_house = 19;
let my_current_apartment = 197;
let my_current_character = 'скверный';
let my_marital_status = 'не женат';
let my_number_of_teeth = 29;
let last_book_read = 'По ком звонит колокол';
let i_drink = true;
//console
console.log('MY_NAME', MY_NAME, typeof MY_NAME);
console.log('MY_MIDDLENAME', MY_MIDDLENAME, typeof MY_MIDDLENAME);
console.log('MY_SURNAME', MY_SURNAME, typeof MY_SURNAME);
console.log('MY_CURRENT_AGE', MY_CURRENT_AGE, typeof MY_CURRENT_AGE);
console.log('MY_HOMETOWN', MY_HOMETOWN, typeof MY_HOMETOWN);
console.log('MY_GENDER', MY_GENDER, typeof MY_GENDER);
console.log('MY_EYE_COLOR', MY_EYE_COLOR, typeof MY_EYE_COLOR);
console.log('I_SMOKE', I_SMOKE, typeof I_SMOKE);
console.log('my_age', my_age, typeof my_age);
console.log('my_current_height', my_current_height, typeof my_current_height);
console.log('my_current_weight', my_current_weight, typeof my_current_weight);
console.log('my_current_nationality', my_current_nationality, typeof my_current_nationality);
console.log('my_current_town', my_current_town, typeof my_current_town);
console.log('my_current_street', my_current_street, typeof my_current_street);
console.log('my_current_house', my_current_house, typeof my_current_house);
console.log('my_current_apartment', my_current_apartment, typeof my_current_apartment);
console.warn('my_current_character', my_current_character, typeof my_current_character);
console.log('my_marital_status', my_marital_status, typeof my_marital_status);
console.log('my_number_of_teeth', my_number_of_teeth, typeof my_number_of_teeth);
console.log('last_book_read', last_book_read, typeof last_book_read);
console.warn('i_drink', i_drink, typeof i_drink);
alert('НЕ ВЫХОДИ ИЗ КОМНАТЫ, НЕ СОВЕРШАЙ ОШИБКУ');
